apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: study-kustomize-dev
spec:
  project: study
  source:
    repoURL: https://github.com/soom-kang/argocd-digging.git
    targetRevision: main
    path: github/6_kustomize_overlay/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: study-kustomize
