spec:
  template:
    spec:
      initContainers:
        - name: rollout-extension
          image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.8
          imagePullPolicy: IfNotPresent
          env:
            - name: EXTENSION_NAME
              value: rollout
            - name: EXTENSION_URL
              value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.7/extension.tar
            - name: EXTENSION_VERSION
              value: v0.3.7
          volumeMounts:
            - name: rollout-extensions
              mountPath: /tmp/extensions/
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
      containers:
        - name: argocd-server
          volumeMounts:
            - name: rollout-extensions
              mountPath: /tmp/extensions/
      volumes:
        - name: rollout-extensions
          emptyDir: {}
