apiVersion: v1
kind: Service
metadata:
  name: sync-window-nginx
  namespace: study-sync-window
spec:
  selector:
    app: sync-window-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
