apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: study-list-generator
spec:
  generators:
    - list:
        elements:
          - appName: team-a
            path: github/08_applicationset_list_generator/apps/team-a
            namespace: study-appset-team-a
          - appName: team-b
            path: github/08_applicationset_list_generator/apps/team-b
            namespace: study-appset-team-b
          # - appName: team-c
          #   path: github/08_applicationset_list_generator/apps/team-c
          #   namespace: study-appset-team-c
  template:
    metadata:
      name: "study-{{appName}}"
    spec:
      project: study
      source:
        repoURL: https://github.com/soom-kang/argocd-digging.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=false
