apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: study-waves-hooks
spec:
  project: study
  source:
    repoURL: https://github.com/soom-kang/argocd-digging.git
    targetRevision: main
    path: github/03_sync_waves_and_hooks
  destination:
    server: https://kubernetes.default.svc
    namespace: study-waves-hooks
